Complete CSS Layout Class - Carolyne Golias
GCarolyne/c1224-code-solutions pull request #33
Opened 2024-12-20 19:20 UTC by GCarolyne

<img width="962" alt="Screenshot 2024-12-20 at 11 14 45 AM" src="https://github.com/user-attachments/assets/9bd33ae3-9b1f-4144-8d45-4dcf8be68250" />
<img width="1007" alt="Screenshot 2024-12-20 at 11 15 04 AM" src="https://github.com/user-attachments/assets/6db57038-c859-47d4-904d-cc4f021427d1" />

2024-12-20 19:22 UTC, shawnkost requested changes
Couple changes here Carolyne!

2024-12-20 19:22 UTC, shawnkost commented on css-layout-classes/index.html
> +        </div>
This shouldn't be a `column-two`. It doesn't take up the same size as the other column. Your text should be a `column-two-thirds` and this should be a `column-third`

2024-12-20 19:22 UTC, shawnkost commented on css-layout-classes/index.html
> +        </div>
Same note as above ^

2024-12-20 20:19 UTC, GCarolyne commented
![Screenshot 2024-12-20 at 12 19 02 PM](https://github.com/user-attachments/assets/a72095a9-f382-41fb-9721-f5b0ff550335)
![Screenshot 2024-12-20 at 12 18 10 PM](https://github.com/user-attachments/assets/f6b4c633-48c9-46ae-9e31-b0a5294e9f1c)

2025-01-06 22:33 UTC, shawnkost approved these changes
👍🏻

2025-01-07 16:55 UTC, merged